language: generic
env:
  matrix:
  - DOCKER_USERNAME=ramonmedeiros
  - secure: vPyza0oWv2t72yFqcchrhyiJgGaFARRWGEn9PSmyldlH9ma7PNOBpRTBUin/LuCwW2nrJ3ve9lq11+p5txpsfJd+j3+KlzVjOSZT67e3LahjYoJ4oIJuVWFLNnAsi8im7NZ9kz0LBK4HM6kgBVx73zaRN+iSGUCdpU5VX9wRh2p0ktF3rZZ1meFwXS2N5Pvj+eSTItQwdnTgZhMndSLDl1ZKbbUpTqg4h4y5TZA11efLbPnnrkMJjF1UD3DDVeEjseuhyHh+kEfYcc/ZeztJ5FWNzmNfn4rZztOBx+xjiIAK99PeFo72X/waks4UE46wOodcs2Sm22+a7/JUQthgXtB2FYdFRftBkr9xFGIaGfdKM6WTWYk5UOZQtvOIfAF6O/XsO+62glgoQDs56bqcTsEPWebKWIlRSz1hVTPrXcDCH+0/ENfED9eK/4WynDjg/e3OxiIzwgvFeBgjeeh1FUnnipv7dTF0I/LlpVUtqcHUsWCK09j9EZ01SJlJb/yQafoRvDycuSq/uJb7qans7QxZ53YaOHv0VymVxZAvppuhoiPMLH3omeSnyCa+MLQTxzFwC+7Q6kGbhotlCUdai8uapiYe5j7iE9bmrbPg8vLpwxU3GUFrxcQnKngnZ89rLhoazGChYGZAM9posZ9ExXe9XyICWfWh8W2GnN3KMDw=
services:
- docker
script:
- make build-container
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- make publish-image
