apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    run: simple-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: node
  type: NodePort

